services:
  hytale:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "${PORT:-5520}:${PORT:-5520}/udp"
    environment:
      - PORT=${PORT:-5520}
      - USE_AOT_CACHE=true
      - ENABLE_AUTO_UPDATE=true
      - SKIP_DELETE_ON_FORBIDDEN=false
      - ACCEPT_EARLY_PLUGINS=false
      - ALLOW_OP=false
      - ASSETS_PATH=/hytale/Assets.zip
      - AUTH_MODE=authenticated
      - BIND_ADDR=0.0.0.0
      - BACKUP_ENABLED=false
      - BACKUP_DIR=/hytale/backups
      - BACKUP_FREQUENCY=30
      - DISABLE_SENTRY=false
    volumes:
      - /srv/${PROJECT_ID:?PROJECT_ID is required}/hytale/data:/hytale
      - /etc/machine-id:/etc/machine-id:ro
    restart: unless-stopped